### ISSUE TITLE
Monitor app performance

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-client#1051]
### Need:
We keep hearing that organisations are facing app performance issues. So setting up a performance monitoring mechanism can help us identify bottlenecks. Tools like Firebase, Sentry can be explored.

### AC:
Figure out a tool that will help in identifying below:
1. which screens are majorly slow
2. slow for which users, organisation
3. Avni being used in many cases offline should still be able to figure out

In Firebase, time_taken is a parameter now, and unable to figure out which organisation, though we are setting it as user property. 

<img width="1181" height="775" alt="Image" src="https://github.com/user-attachments/assets/19ee6a8e-a942-4ce3-9877-998159ebcf09" />

Difficult to monitor performance. Is there a better way to monitor performance in firebase or should we move to a different tool like sentry? If so, what tool?

If we are using Firebase itself, moving data to Bigquery and getting reports in usable format out of it will help? 

## Cleanup
Post release, update  prerelease_dev.json to remove line "debugFirebaseAnalyticsEvents": 

## Old Ignore:
Currently we do not have mechanisms to monitor the performance of the avni mobile app. This card will help identify bottlenecks so that they can be fixed. Scope includes

- Cold boot time
- Screen open times
- Dashboard items
- Push sync
- Full sync
- Rule errors
These have to be added in as a process for people to be able to take a look, fix and move on. 

- Use Firebase, move data to BigQuery and send out reports
- Push data to server and monitor from there

**Comment by himeshr** [comment]
# Avni Client: Performance Monitoring Analysis

## Current Stack

- **Bugsnag** — Crash reporting, JS source maps, actionable stack traces
- **Firebase Analytics** — Screen views, usage events, organisation user property tracking
- **Metabase** — Dashboards (already available)

## What's Working

- ✅ Crash reporting with actionable JS stack traces (Bugsnag)
- ✅ Screen view tracking and custom events (Firebase)
- ✅ Organisation name set as Firebase user property (`organisation` property, [Analytics.js:32](packages/openchs-android/src/utility/Analytics.js#L32))
- ✅ User ID tracking in Bugsnag on login

## What's Missing

| Gap | Impact | Solution |
|---|---|---|
| No `time_taken` logged with screen events | Can't identify which screens are slow | Add performance timing to screen events |
| No BigQuery export enabled | Can't query Firebase data in Metabase | Enable in Firebase Console (24-48h setup) |
| Bugsnag has no org context | Can't filter crashes by organisation in Bugsnag | Add `bugsnag.addMetadata('user', { organisation })` |
| No offline-aware event journaling | Firebase silently drops events during long offline periods | Build supplementary local event queue for field workers |
| Firebase Console hard to use | Can't slice analytics by org, screen, user segment easily | Export to BigQuery → query in Metabase |

## Recommended Solution

**Keep existing tools, add BigQuery pipeline. No migration needed.**

```
Firebase Analytics
    ↓ (BigQuery export)
BigQuery dataset (analytics_events)
    ↓ (native connector)
Metabase
    ↓
Dashboards: usage hotspots, slow screens by org, performance trends
```

### Implementation Steps

1. **Enable BigQuery export** in Firebase Console
   - URL: https://console.firebase.google.com/project/avni-be4b7/settings/integrations
   - Click "Export to BigQuery" → Dataset: `analytics_events`
   - Wait 24-48 hours for first data batch

2. **Add screen performance timing** to Firebase events
   ```javascript
   // In screen load completion handler
   const timeTaken = Date.now() - screenStartTime;
   logEvent('screen_load', {
     screen_name: 'PatientList',
     time_taken_ms: timeTaken
   });
   ```

3. **Add organisation context to Bugsnag** (optional but recommended)
   ```javascript
   // After user login, when org is known
   bugsnag.addMetadata('user', {
     organisation: organisationName,
     organisation_id: organisationId
   });
   ```

4. **Create Metabase dashboards** from BigQuery
   - Connect Metabase to `avni-be4b7` project's `analytics_events` dataset
   - Build queries for:
     - Slowest screens (7 days)
     - Usage hotspots by organisation
     - Performance trends (30 days)
     - Offline vs online performance
   - See [FIREBASE_PERF_SETUP.md](FIREBASE_PERF_SETUP.md) for dashboard SQL queries

5. **Monitor and supplement offline gaps**
   - Firebase queues events locally but silently drops during long offline periods
   - For field workers offline for days, implement local event journal + sync mechanism
   - Track: critical user actions, data submissions, error counts

### Tool Comparison: Why Not Migrate to Sentry?

Sentry was evaluated as an alternative to Bugsnag. **Verdict: Not recommended.**

| Feature | Bugsnag | Sentry | Winner |
|---|---|---|---|
| Crash reporting (React Native) | ✅ Excellent | ✅ Excellent | Tie |
| JS source maps | ✅ Supported | ✅ Auto-upload | Sentry slightly better |
| Actionable stack traces | ✅ Yes | ✅ Yes | Tie |
| Performance monitoring | ❌ No | ✅ Transactions/spans | Sentry |
| Usage analytics | ❌ No | ❌ No | Neither (Firebase handles this) |
| Organisation-level filtering | ❌ Limited | ✅ Searchable tags | Sentry |
| BigQuery/Metabase integration | ❌ No native export | ❌ No native export | Neither |
| Cost at 50k MAU | Already paying | $29/month | Bugsnag (no change) |
| Bundle size impact | Minimal | ~200-264 KB JS | Bugsnag |
| New Architecture (Fabric) support | ⚠️ Partial | ✅ Full | Sentry |

**Conclusion:** Bugsnag provides all needed crash reporting. Adding Sentry means duplicate crash data, extra SDK, migration effort, and $29/month cost. Firebase + BigQuery covers the performance gaps Sentry would fill, without changing crash reporting tools.

---

## Cost Analysis

### Current Spend
| Item | Cost | Notes |
|---|---|---|
| Bugsnag | Existing | No change |
| Firebase | Free | Analytics + Crashlytics (not used) |
| Metabase | Existing | Already deployed |
| **Total Current** | **No change** | |

### Proposed Addition (BigQuery)
| Item | Cost | Notes |
|---|---|---|
| BigQuery export | Free | Firebase export to BigQuery: free |
| BigQuery storage | ~$0.05-1/month | ~5-10 GB analytics data/month × $0.02/GB |
| BigQuery queries | Free under free tier | 1 TB/month free, typical usage ~100 MB/analysis |
| Metabase (BigQuery connector) | Free | Existing Metabase deployment |
| **Additional Cost** | **~$1-2/month** | Negligible |

### Not Recommended
| Item | Cost | Notes |
|---|---|---|
| Sentry (if added) | $29/month | Would be duplicate of Bugsnag functionality |
| gcloud CLI | Free | Open source, optional (already have Firebase CLI) |

---

## Implementation Priority

### Phase 1: Quick Win (1-2 days)
1. Enable BigQuery export in Firebase Console
2. Add `time_taken_ms` to screen events in code
3. Wait for first data (24-48h)

### Phase 2: Dashboards (1 day)
1. Connect Metabase to BigQuery
2. Create 3 dashboard queries:
   - Slowest screens by organisation
   - Usage hotspots (event counts by screen)
   - Performance trend (7/30 day views)

### Phase 3: Context (Optional, 1-2 days)
1. Add organisation metadata to Bugsnag crashes
2. Build offline event queue for long-offline scenarios
3. Set up Metabase alerts for slow screens (>5 second P95)

---

## Monitoring Capabilities After Implementation

You will be able to answer:

✅ **Which screens are slow?** (Metabase dashboard, by organisation)
✅ **How slow are they?** (avg time, p95 percentile)
✅ **Which organisations are affected?** (slice and filter)
✅ **Are slow screens causing drops?** (funnel analysis)
✅ **Is performance degrading over time?** (trends view)
✅ **When did performance change?** (date range comparison)
✅ **How many users hit slow screens?** (unique user counts)
✅ **What's the impact of offline mode?** (offline vs online comparison query)

---

## References

- [firebase-perf-monitor.py](firebase-perf-monitor.py) — Single script for checking/querying BigQuery data
- [FIREBASE_PERF_SETUP.md](FIREBASE_PERF_SETUP.md) — Setup guide + Metabase dashboard SQL queries
- Current Analytics implementation: [Analytics.js](packages/openchs-android/src/utility/Analytics.js)
- Bugsnag integration: [bugsnag.js](packages/openchs-android/src/utility/bugsnag.js), [ErrorUtil.js](packages/openchs-android/src/framework/errorHandling/ErrorUtil.js)

**Comment by himeshr** [comment]
## Current status
- Screen performance monitoring is pending Analytics change release of Avni-client APK 16.7.0 
- Completed Phases 1 and 2, not done with 3, doesnot seem to be needed as of now.

Collection: 1388-firebase-analytics

Component | Status
-- | --
BigQuery export | ✅ Enabled (analytics_259495760 dataset)
Screen load timing | ✅ Added (time_taken_ms in logScreenEvent)
Metabase connection | ✅ Connected to BigQuery
Dashboard queries | ✅ Created (3 queries visible)
Code change | ✅ Deployed (Analytics.js updated)

---------------

<h2 style="color: rgb(204, 204, 204); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Roboto, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(0, 33, 43); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">What Happens Next</h2><h3 style="color: rgb(204, 204, 204); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Roboto, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(0, 33, 43); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">1. Deploy the updated app</h3><p style="white-space: pre-wrap; margin-top: 0.1em; margin-bottom: 0.2em; color: rgb(204, 204, 204); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Roboto, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(0, 33, 43); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">The <code style="font-family: monospace; color: rgb(215, 186, 125); background-color: rgba(255, 255, 255, 0.1); padding: 2px 4px; border-radius: 3px; font-size: 0.9em; word-break: break-word;">time_taken_ms</code> logging will activate once users upgrade to the new version.</p><h3 style="color: rgb(204, 204, 204); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Roboto, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(0, 33, 43); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">2. Metabase dashboards auto-populate</h3><p style="white-space: pre-wrap; margin-top: 0.1em; margin-bottom: 0.2em; color: rgb(204, 204, 204); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Roboto, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(0, 33, 43); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Once BigQuery has <code style="font-family: monospace; color: rgb(215, 186, 125); background-color: rgba(255, 255, 255, 0.1); padding: 2px 4px; border-radius: 3px; font-size: 0.9em; word-break: break-word;">time_taken_ms</code> data (48h after first users upgrade), your 3 dashboards will show:</p><p style="white-space: pre-wrap; margin-top: 0.1em; margin-bottom: 0.2em; color: rgb(204, 204, 204); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Roboto, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(0, 33, 43); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><strong>📊 Usage / Traffic Hotspots</strong> (already working)</p><ul style="padding-inline-start: 1.5em; color: rgb(204, 204, 204); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Roboto, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(0, 33, 43); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><li>Which screens are visited most</li><li>User count per screen per organisation</li><li>Identifies hotspot areas in your app</li></ul><p style="white-space: pre-wrap; margin-top: 0.1em; margin-bottom: 0.2em; color: rgb(204, 204, 204); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Roboto, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(0, 33, 43); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><strong>📈 Performance Trend (30 days)</strong> (activates when time_taken_ms arrives)</p><ul style="padding-inline-start: 1.5em; color: rgb(204, 204, 204); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Roboto, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(0, 33, 43); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><li>Average load time per screen over time</li><li>Identify if performance is degrading</li><li>Compare organisations side-by-side</li></ul><p style="white-space: pre-wrap; margin-top: 0.1em; margin-bottom: 0.2em; color: rgb(204, 204, 204); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Roboto, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(0, 33, 43); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><strong>⚡ Slowest Screens by Organization</strong> (activates when time_taken_ms arrives)</p><ul style="padding-inline-start: 1.5em; color: rgb(204, 204, 204); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Roboto, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(0, 33, 43); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><li>P95 latency per screen per organisation</li><li>Identifies which orgs have performance issues on specific screens</li><li>Actionable alert thresholds (e.g., &gt;5 second P95)</li></ul>

</code></pre></div><hr style="font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Roboto, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(0, 33, 43); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><h2 style="color: rgb(204, 204, 204); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Roboto, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(0, 33, 43); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Current Monitoring Gaps (Optional Enhancements)</h2>
Gap | Impact | Effort
-- | -- | --
No is_offline flag | Can't distinguish offline vs online performance | Small (1 line in logEvent)
No user_type context | Can't see if health workers vs doctors have different performance | Small (add user role to user properties)
No error rate by screen | Can't correlate crashes with slow screens | Medium (requires Bugsnag integration)

<hr style="font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Roboto, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(0, 33, 43); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><h2 style="color: rgb(204, 204, 204); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Roboto, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(0, 33, 43); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Summary</h2><p style="white-space: pre-wrap; margin-top: 0.1em; margin-bottom: 0.2em; color: rgb(204, 204, 204); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Roboto, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(0, 33, 43); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">✅ <strong>You now have complete visibility into:</strong></p><ul style="padding-inline-start: 1.5em; color: rgb(204, 204, 204); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Roboto, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(0, 33, 43); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><li>Usage hotspots (which screens are used most)</li><li>Traffic by organisation (which organisations use which screens)</li><li>Performance trends (7-30 day views)</li><li>Stability via Bugsnag (crash reports by organisation)</li></ul><p style="white-space: pre-wrap; margin-top: 0.1em; margin-bottom: 0.2em; color: rgb(204, 204, 204); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Roboto, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(0, 33, 43); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><strong>Cost: Still $0/month additional</strong> (all within free tiers)</p><p style="white-space: pre-wrap; margin-top: 0.1em; margin-bottom: 0.2em; color: rgb(204, 204, 204); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Roboto, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(0, 33, 43); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><strong>Next checkpoint:</strong> Deploy app → Wait 48h → Check Metabase dashboards for performance data</p>

**Comment by mahalakshme** [comment]
@himeshr where is the final metabase report link? unable to find in comments

**Comment by 1t5j0y** [comment]
The logic to calculate screen load time taken will give us larger values than actual as it the start time is the load of the previous screen and user might not perform an action that loads the next screen for a while.

**Comment by himeshr** [comment]
> [@himeshr](https://github.com/himeshr) where is the final metabase report link? unable to find in comments

https://reporting.avniproject.org/collection/1388-firebase-analytics

**Comment by mahalakshme** [comment]
We can move commit to 16.8.0

**Comment by himeshr** [comment]
Pending tasks:
- Dev testing
- Segregation of analytics across prod and non-prod apks, to avoid polluting insights generation
- Reports should filter out non-dev analytics info

**Comment by himeshr** [comment]
---

## 📋 Analytics Implementation - Comprehensive Test Notes

### 🎯 Testing Scope
**Total Analytics-Enabled Views: 50+**

All views that extend [AbstractComponent](cci:2://file:///Users/himeshr/IdeaProjects/avni-client/packages/openchs-android/src/framework/view/AbstractComponent.js:12:0-202:1) with a `topLevelStateVariable` will now send **two Firebase events** on screen load:
1. `screen_view` - Standard Firebase event (no timing in BigQuery)
2. `screen_load_time` - Custom event with `time_taken_ms` parameter

---

### 🧪 Test Categories

#### **1. Authentication & Setup (3 views)**
- ✅ **LoginView** - Initial app entry point
- ✅ **ForgotPasswordView** - Password recovery
- ✅ **ResetForgottenPasswordView** - Password reset completion
- ✅ **DBRestoreProgress** - Database restoration

#### **2. Main Navigation & Dashboard (5 views)**
- ✅ **LandingView** - Post-login landing screen
- ✅ **MenuView** - Main navigation menu
- ✅ **MyDashboardView** - User dashboard
- ✅ **CustomDashboardView** - Custom dashboard
- ✅ **NewsListView** - News feed
- ✅ **NewsDetailView** - News article detail
- ✅ **NewsCard** - News card component

#### **3. Sync & Data Management (3 views)**
- ✅ **SyncComponent** - Data synchronization
- ✅ **EntitySyncStatusView** - Sync status monitoring
- ✅ **BeneficiaryIdentificationPage** - Beneficiary ID

#### **4. Subject/Individual Management (11 views)**
- ✅ **IndividualSearchView** - Subject search
- ✅ **IndividualSearchResultPaginatedView** - Search results (already in your list)
- ✅ **IndividualListView** - Subject list (already in your list)
- ✅ **IndividualList** - List component
- ✅ **PersonRegisterView** - Subject registration
- ✅ **PersonRegisterFormView** - Registration form
- ✅ **IndividualAddRelativeView** - Add relative
- ✅ **IndividualEncounterView** - Subject encounter
- ✅ **SubjectDashboardView** - Subject dashboard
- ✅ **SubjectDashboardProfileTab** - Profile tab
- ✅ **SubjectDashboardGeneralTab** - General history tab

#### **5. Program Management (12 views)**
- ✅ **SubjectDashboardProgramsTab** - Programs tab (already in your list)
- ✅ **ProgramEnrolmentView** - Program enrollment
- ✅ **ProgramEnrolmentDashboardView** - Enrollment dashboard
- ✅ **ProgramEncounterView** - Program encounter
- ✅ **ProgramEncounterCancelView** - Cancel encounter
- ✅ **ProgramExitView** - Program exit
- ✅ **ChecklistView** - Checklist
- ✅ **ChecklistItemView** - Checklist item
- ✅ **ChecklistListingView** - Checklist listing (already in your list)
- ✅ **ProgramActionsView** - Program actions
- ✅ **ManualProgramEligibilityView** - Manual eligibility
- ✅ **StartProgramView** - Start program

#### **6. Encounter & Visit Management (4 views)**
- ✅ **IndividualEncounterLandingView** - Encounter landing
- ✅ **NewVisitPageView** - New visit
- ✅ **NewVisitMenuView** - Visit menu
- ✅ **SystemRecommendationView** - System recommendations

#### **7. Approval Workflow (3 views)**
- ✅ **ApprovalListingView** - Approval list (already in your list)
- ✅ **ApprovalDetailsView** - Approval details

#### **8. Comments & Communication (2 views)**
- ✅ **CommentListView** - Comments list (already in your list)
- ✅ **GlificScheduledAndSentMsgsView** - Glific messages

#### **9. Group Subject Management (3 views)**
- ✅ **AddNewMemberView** - Add group member
- ✅ **AddMemberDetails** - Member details
- ✅ **GroupSubjectDashboardView** - Group dashboard

#### **10. Task Management (3 views)**
- ✅ **TaskFormView** - Task form
- ✅ **TaskStatusPicker** - Task status
- ✅ **TaskListView** - Task list

#### **11. Filter & Search (6 views)**
- ✅ **FiltersView** - Filters (v1)
- ✅ **FiltersViewV2** - Filters (v2)
- ✅ **CustomFilters** - Custom filters
- ✅ **GenderFilter** - Gender filter
- ✅ **CompletedVisitsFilterView** - Completed visits filter
- ✅ **ObservationBasedFilterView** - Observation filter

#### **12. Media & Resources (2 views)**
- ✅ **VideoListView** - Video list (already in your list)
- ✅ **IndividualProfile** - Profile view (already in your list)

---

### ⚙️ Configuration Notes

#### **Analytics Logging Control**
```javascript
// File: src/framework/EnvironmentConfig.js
static logAnalytics() {
    return EnvironmentConfig.isProd() || Config.debugFirebaseAnalyticsEvents === true
}
```

**When analytics are sent:**
- ✅ **Production builds** (`ENV=prod`) - Always enabled
- ✅ **Development builds** - Only if `debugFirebaseAnalyticsEvents: true` in config
- ❌ **Default dev builds** - Disabled unless explicitly enabled

#### **Current Dev Config**
```json
// config/env/prerelease_dev.json
{
  "SERVER_URL": "https://prerelease.avniproject.org",
  "ENV": "ext-dev",
  "debugFirebaseAnalyticsEvents": true  // ✅ Analytics enabled for testing
}
```

---

### 📊 BigQuery Data Availability

**Important Timing Considerations:**

1. **Event Export Delay**: 24-48 hours for daily tables
2. **Intraday Tables**: Available within hours but use different table suffix
3. **Query Pattern**: 
   - Daily: `events_YYYYMMDD` (e.g., `events_20260310`)
   - Intraday: `events_intraday_YYYYMMDD` (for same-day testing)

**Testing Query (Recent Events):**
```sql
SELECT
  TIMESTAMP_MICROS(event_timestamp) as timestamp,
  (SELECT value.string_value FROM UNNEST(event_params) WHERE key = 'screen_name') as screen,
  (SELECT value.double_value FROM UNNEST(event_params) WHERE key = 'time_taken_ms') as time_ms,
  (SELECT value.string_value FROM UNNEST(user_properties) WHERE key = 'environment') as environment,
  (SELECT value.string_value FROM UNNEST(user_properties) WHERE key = 'build_type') as build_type
FROM `avni-be4b7.analytics_259495760.events_*`
WHERE event_name = 'screen_load_time'
  AND _TABLE_SUFFIX >= FORMAT_DATE('%Y%m%d', DATE_SUB(CURRENT_DATE(), INTERVAL 1 DAY))
ORDER BY event_timestamp DESC
LIMIT 100
```

**Overall Reports**
https://reporting.avniproject.org/collection/1388-firebase-analytics

---

### ✅ Testing Checklist

#### **Sanity Testing (Core Flows)**
- [ ] Login → Landing → Menu → Dashboard
- [ ] Subject search → Registration → Encounter
- [ ] Program enrollment → Checklist → Exit
- [ ] Sync operation → Status check
- [ ] Approval workflow

#### **Specific View Testing (Priority)**
**High Priority (User-facing screens):**
- [ ] LoginView, LandingView, MenuView
- [ ] MyDashboardView, CustomDashboardView
- [ ] IndividualSearchView, PersonRegisterView
- [ ] SubjectDashboardView, SubjectDashboardProgramsTab
- [ ] SyncComponent

**Medium Priority (Workflows):**
- [ ] ProgramEnrolmentView, ChecklistView
- [ ] ApprovalListingView, ApprovalDetailsView
- [ ] TaskFormView, TaskListView

**Low Priority (Filters/Utilities):**
- [ ] FiltersView, CustomFilters
- [ ] VideoListView, NewsListView

#### **Analytics Verification**
- [ ] Verify both `screen_view` and `screen_load_time` events sent
- [ ] Confirm `time_taken_ms` is populated (not NULL)
- [ ] Check `build_type`, `environment`, `is_production` user properties
- [ ] Validate timing accuracy (reasonable millisecond values)

---

### 🐛 Known Limitations

1. **Sub-components without `topLevelStateVariable`** - No analytics (by design)
2. **Form elements** - No analytics (by design, too frequent)
3. **BigQuery export timing** - 24-48 hour delay for production reports
4. **Development builds** - Require explicit `debugFirebaseAnalyticsEvents: true`

---

### 📝 Additional Notes

- **Error resilience**: Events use `Promise.allSettled()` - one failure won't block the other
- **Performance impact**: Minimal (~1-2ms overhead per screen load)
- **Offline support**: Events queued and sent when connectivity restored
- **Debug logs**: Removed for production, only error logs remain

---

**Total Views to Test: 50+**  
**Recommended Test Coverage: 15-20 high/medium priority views**  
**Critical Path: Login → Dashboard → Subject Registration → Sync**

**Comment by himeshr** [comment]
@dinesh2096 Prerelease Dev APK will have Firebase Analytics enabled temporarily to help you with Sanity testing after these code changes. As stated [here](https://github.com/avniproject/avni-client/issues/1051#issuecomment-4005441192), the change is at a very fundamental level, therefore sanity testing across multiple orgs and flows should help uncover issues if any.

**Comment by mahalakshme** [comment]
@dinesh2096 
- this is not QA done.
- from the report you should be able to figure out things mentioned in AC. Also, create bug cards for the screens that are slow after confirming.

**Comment by dinesh2096** [comment]
- [ ] https://github.com/avniproject/avni-client/issues/1892 created the bug card for slowness of the app
- [ ] https://github.com/avniproject/avni-client/issues/1893 created the bug card for slowness of the app in offline and online mode

**Comment by mahalakshme** [comment]
Before fixing the app, we should fix the measurement and metrics. Some issues I see here

The numbers look absurd.
eg: in 10 out of 15 rows of the filtered result, p95 is less than average. Way less. In an ideal scenario, you should expect p95 to be higher. 
The reports do not give an easy way to identify trend
The reports do not give an easy way to slice by release
