### ISSUE TITLE
Ease navigation/filtering for approval type cards

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-client#1194]
Documentation on Custom Dashboards: 
https://avni.readme.io/docs/custom-dashboards-and-report-cards

```[tasklist]
### Tasks
- [ ] https://github.com/avniproject/avni-client/issues/1183
- [ ] https://github.com/avniproject/avni-client/issues/1185
- [ ] https://github.com/avniproject/avni-client/issues/1186
- [ ] https://github.com/avniproject/avni-client/issues/1189
```
