### ISSUE TITLE
Bug fixes

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-client#1421]
```[tasklist]
### Tasks
- [ ] https://github.com/avniproject/avni-client/issues/1420
- [ ] https://github.com/avniproject/avni-client/issues/1438
- [ ] https://github.com/avniproject/avni-client/issues/1439
- [ ] https://github.com/avniproject/avni-webapp/issues/1269
- [ ] https://github.com/avniproject/avni-client/issues/1435
- [ ] https://github.com/avniproject/avni-server/issues/740
- [ ] https://github.com/avniproject/avni-client/issues/1458
- [ ] https://github.com/avniproject/avni-server/issues/744
- [ ] https://github.com/avniproject/avni-webapp/issues/1260
- [ ] https://github.com/avniproject/avni-client/issues/1470
```
