### ISSUE TITLE
Misc bug/issue fixes

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-client#1465]
```[tasklist]
### Tasks
- [ ] https://github.com/avniproject/avni-models/issues/53
- [ ] https://github.com/avniproject/avni-webapp/issues/1336
- [ ] https://github.com/avniproject/avni-etl/issues/75
- [ ] https://github.com/avniproject/avni-webapp/issues/1257
- [ ] https://github.com/avniproject/avni-client/issues/1477
- [ ] https://github.com/avniproject/avni-webapp/issues/1208
- [ ] https://github.com/avniproject/avni-webapp/issues/1320
- [ ] https://github.com/avniproject/avni-infra/issues/43
- [ ] https://github.com/avniproject/avni-webapp/issues/1348
- [ ] https://github.com/avniproject/avni-client/issues/1523
- [ ] https://github.com/avniproject/avni-client/issues/1100
- [ ] https://github.com/avniproject/avni-client/issues/1534
- [ ] https://github.com/avniproject/avni-webapp/issues/1180
- [ ] https://github.com/avniproject/avni-webapp/issues/1316
- [ ] https://github.com/avniproject/avni-webapp/issues/1351
- [ ] https://github.com/avniproject/avni-webapp/issues/1366
- [ ] https://github.com/avniproject/avni-server/issues/815
- [ ] https://github.com/avniproject/avni-infra/issues/45
- [ ] https://github.com/avniproject/avni-client/issues/1540
```
