### ISSUE TITLE
Implementation of dashboard filters on standard report cards

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-client#912]
### Need
- To apply filters on standard report cards added to custom cards - Eg: currently found in JSSCP, APF odisha
- To unify the dashboard and filters code in one place to be able to do refactoring/improvements in one place.

### Utility:
- There are 5 orgs where standard cards are part of custom dashboard - APF, JSCS, sakhiapp, PoWER, CTRITH_IPH
- now can this standard cards be moved out - no - 3 are primary dashboards - sakhi app(no filters configured), JSCS, PoWER, RWB
- So orgs want standard cards to be part of custom dashboard
- Among the above orgs RWB, PoWER only use location filter and APF needs - so is it really useful? whats the utility as an org we are getting?  easy maintenance of the code(all features of MyD on CD), features on MyDashboard on CD, can add more new features like card wise refresh more flexibily, add more flexibility

```[tasklist]
### Tasks
- [ ] https://github.com/avniproject/avni-webapp/issues/1203
- [ ] https://github.com/avniproject/avni-client/issues/1381
- [ ] https://github.com/avniproject/avni-webapp/issues/1204
- [ ] https://github.com/avniproject/avni-client/issues/1382
- [ ] https://github.com/avniproject/avni-webapp/issues/1263
- [ ] https://github.com/avniproject/avni-client/issues/1436
- [ ] https://github.com/avniproject/avni-client/issues/1437
```

### Stories
- Below filters need to work on standard report card added to custom dashboard:
         - subject type, concepts, encounter type, program, registeration date, enrolment date, program encounter date, encounter date
- Remove MyDashboard filters on the UI in webapp
- support disable auto refresh on custom dashboard.
- Migrate myDashboardFilters in organisation_config table to dashboard filter table and make sure it works.
- Add myDashboard via customDashboard when creating an org.
- Being able to pass subject/program by implementor - configure in App designer when selecting SRC

### Tech tasks
- Sync of dashboard filter to app
- Refactor standard report cards used by Custom Dashboard to use filters that are currently being applied on MyDashboard

### Questions:
- Why is this a priority now for product team? Since doesn't seem to be needed by users now.
- have users with SRC on Custom dashboard as primary dashboard asked other filters?
- Registration and EnrolmentDateTime only for swadhar
- Subject type filter on custom dashboard - how much relevant? - APF odisha - already split based on subject types except for few cards - inline with Avni design guidelines?

### Testing
- Test for all filter types individually. Behavior should be same as current MyDashboard. 
- Test for multiple filter types being applied together. Behavior should be the same as current MyDashboard
- Test with and without the parameters applied on the standard report card types (if the parameters card has been played)

**Comment by petmongrels** [comment]
Moving back to analysis.
https://docs.google.com/document/d/1lCN2B-uXDl_EarofgUAm3PaU5UajX6cdd4pB47hPJ_g/edit

**Comment by mahalakshme** [comment]
duplicate
