### ISSUE TITLE
[avni-client] Editable field doesn't work as expected with auto-populated value by the rule

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/avni-client#973]
**Freshdesk support ticket** - https://avni.freshdesk.com/a/tickets/2658

**Expectation** - 
- When a editable field value is set by a rule, then value calculated by the rule should be shown in the field
- When the field value(autocalculated value) is edited, the manually entered value should be saved and the rules should be executed for the manually entered value

**Reality**
- Value calulated by the rule displays only when the field is readonly, 
- Though it doesn't display the autocalculated value for editable fields,  the autocalculated value is saved and the rule is executed for the auto-calculated value
- The manually entered value is not considered
- The above causes confusion

**Analysis:**
- The below analysis is for numeric form elements. When fixing, other form elements like Text also need to be considered.
- The issue has happened because we are currently not considering that editable value can also be autopopulated by rules. So the below needs to be done to fix the same.
     -  In NumericFormElement.js, when returning JSX, and when the field is editable, need to modify the code for value like below: `value={_.isEmpty(this.state.value) ? _.toString(this.props.value.getValue()) : this.state.value }`. This will take care of showing the autocalculated value and allowing it to be edited.
     - Even after the above, entered value is not saved. So to do that, In ObserverHolderActions.js, we are overriding the entered value with autocalculated value when doing this: `newState.observationsHolder.updatePrimitiveCodedObs(newState.filteredFormElements, formElementStatuses)`. Hence when the `newState.observationsHolder.observations` already has value for a concept, value calculated from the rule should not be overwritten.
     - Also when finding of `ruleValidationErrors` in ObserverHolderActions.js, when entered value for a concept is there, we should not validate for the auto-calculated value.
- UX: When autocalculated value needs to be edited, in this case 90 to 1, the user might find it not easy to edit. Since when the field becomes empty it will get populated, the user needs to leave a part of the number to be able to edit, then clear the left part later. (It might be possible to fix this issue via code changes - need to investigate)
   https://images.zenhubusercontent.com/64590403/d0d77051-f792-4a47-9f3a-a65adf549706/screen_recording_2023_05_17_at_6_54_06_pm.mov 
- Is it regression issue:
        - As part of #697 story, commits(73e568a6, bedf4b7e) could have broke this if this was already working.

**Stories:**
- [x] avniproject/avni-client#974
- [ ] avniproject/avni-product#1340
- [x] avniproject/avni-client#1037
